### ISSUE TITLE
CWD is not in search path in non-interactive mode

### ISSUE THREAD

**Issue by drsm** [nginx/njs#114]
```js
$ pwd
/home/drsm/work/njs
$ head test.js bug.js 
==> test.js <==
import bug from 'bug.js';

==> bug.js <==
export default { bug: true };
$ build/njs test.js 
SyntaxError: Cannot find module "bug.js" in test.js:1
$ build/njs -p . test.js 
$ build/njs
interactive njs 0.3.0

v.<Tab> -> the properties and prototype methods of v.
type console.help() for more information

>> import bug from 'bug.js';
undefined
>> bug
{
 bug: true
}
>>
```

**Comment by hongzhidao** [comment]
@drsm good reporting.

Try the patch please.
```
diff -r 53dc000e8c14 njs/test/njs_unit_test.c
--- a/njs/test/njs_unit_test.c	Sat Mar 02 20:31:10 2019 +0800
+++ b/njs/test/njs_unit_test.c	Sat Mar 23 14:34:40 2019 +0800
@@ -12456,13 +12456,13 @@ nxt_file_dirname_test(njs_vm_t * vm, nxt
         nxt_str_t   path;
         nxt_str_t   expected;
     } tests[] = {
-        { nxt_string(""),               nxt_string("") },
+        { nxt_string(""),               nxt_string(".") },
         { nxt_string("/"),              nxt_string("/") },
         { nxt_string("/a"),             nxt_string("/") },
         { nxt_string("///"),            nxt_string("///") },
         { nxt_string("///a"),           nxt_string("///") },
         { nxt_string("///a/"),          nxt_string("///a") },
-        { nxt_string("a"),              nxt_string("") },
+        { nxt_string("a"),              nxt_string(".") },
         { nxt_string("a/"),             nxt_string("a") },
         { nxt_string("a//"),            nxt_string("a") },
         { nxt_string("p1/p2/name"),     nxt_string("p1/p2") },
diff -r 53dc000e8c14 nxt/nxt_file.c
--- a/nxt/nxt_file.c	Sat Mar 02 20:31:10 2019 +0800
+++ b/nxt/nxt_file.c	Sat Mar 23 14:34:40 2019 +0800
@@ -38,8 +38,7 @@ nxt_file_dirname(const nxt_str_t *path,
     const u_char  *p, *end;

     if (path->length == 0) {
-        *name = nxt_string_value("");
-        return;
+        goto current_dir;
     }

     p = path->start + path->length - 1;
@@ -51,8 +50,7 @@ nxt_file_dirname(const nxt_str_t *path,
     end = p + 1;

     if (end == path->start) {
-        *name = nxt_string_value("");
-        return;
+        goto current_dir;
     }

     /* Stripping trailing slashes. */
@@ -67,4 +65,10 @@ nxt_file_dirname(const nxt_str_t *path,

     name->start = path->start;
     name->length = p - path->start;
+
+    return;
+
+current_dir:
+
+    *name = nxt_string_value(".");
 }
```

**Comment by hongzhidao** [comment]
@xeioex 

Take a look.
https://linux.die.net/man/1/dirname
```
Description
Print NAME with its trailing /component removed; if NAME contains no /'s, output '.' (meaning the current directory).
```
Confirm whether the above is an issue please.

**Comment by xeioex** [comment]
> BTW, what's the cause of this problem?

It turned out to be a long story:

```diff
--- a/njs/njs_parser.c
+++ b/njs/njs_parser.c
@@ -2001,7 +2001,8 @@ njs_parser_module_lambda(njs_vm_t *vm, n
         return NJS_TOKEN_ERROR;
     }
 
-    parser->scope->module = 1;
+    node->scope = parser->scope;
+    node->scope->module = 1;
```

My fix fixed one problem with backtraces, but introduced a tricky problem to debug.
The bug only manifested itself on x86,  so I came to conclusion, as it was before, that somehow we got another alignment issue. 

For `njs_value_t` pointers it is crucial to be aligned to 16 bytes, otherwise the following code would not work as expected for absolute scope variables (for such variables index is simply it pointer)

```c
#define njs_vmcode_operand(vm, index)                                         \
    ((njs_value_t *)                                                          \
     ((u_char *) vm->scopes[(uintptr_t) (index) & NJS_SCOPE_MASK]             \
      + njs_scope_offset(index)))
```

Because, njs_value_t can be stored in other structures, it is [important](https://github.com/nginx/njs/blob/master/njs/njs_function.c#L351) to align those structs as well.

On x86 the bug manifest itself as a corrupter ptr [here](https://github.com/nginx/njs/blob/master/njs/njs_vm.c#L176) after FUNCTION instruction (corresponds to import `function(){}` wrapper). so whether `vm->scopes[]` or `index` was corrupted. In fact, `vm->scopes[]` were corrupted (with uninitialised value), but again only on x86.
I started to dig down the issue and found out that on x86_64 the issue was hidden by other memory overflow bug ([here](https://github.com/nginx/njs/blob/master/njs/njs.c#L425))  (it seems  size is not correctly calculated, so njs_builtin_objects_clone() overwrites to vm->scopes[]), which fixed the issue with uninitialised `vm->scopes[]`.

Only after I realised it, I looked into index value, which was something, 0x144, the last 0x4 is important, it is the scope (4 - local scope). But, there should no be local variables in global scope :) Finally, I traced down the place where scope index was given and why it was local index.  Finally, I came to conclusion that FUNCTION instruction should be in its enclosing scope (as it in other places and was originally). Finally, I fixed the backtrace issue in njs_generate_function().
