### ISSUE TITLE
for loop performance concerns

### ISSUE THREAD

**Issue by vryabinin** [nginx/njs#301]
A small synthetic test.
```javascript
for (var i = 0; i < 1e9; i++) {
}
```

Node.js v13.11.0: 440ms
njs@e6d5690:      17008ms

Just wondering, why such a difference?

CentOS 8 Linux 4.18.0-80.el8.x86_64, 4GB RAM, Intel Core i7-4790K@4.00GHz

**Comment by xeioex** [comment]
> Just wondering, why such a difference?

node.js uses V8 which compiles JS code into the native x86.
njs is an interpreter (like CPython implementation of python).

**Comment by xeioex** [comment]
@vryabinin

Just wondering, why such a difference?

node.js uses V8 which compiles JS code into the native x86.
njs is an interpreter (like CPython implementation of python).

See for the reference https://bellard.org/quickjs/bench.html

The conclusions are:

njs is not the the best for heavy-weight math and CPU intensive operations.
njs works the best as a glue code for nginx.
njs+nginx does not plan to replace node.js, njs is used to extend the functionality of nginx.
njs is better to compare with openresty ecosystem but with JS instead of lua.

**Comment by drsm** [comment]
@vryabinin 

Also, constant expressions are not optimized, it's better to avoid them in a loop.

```shell
$ cat y.js
console.time(1);
for (var i = 0; i < 1e9; i++) {
}
console.timeEnd(1);

console.time(2);
for (var i = 0; i < 10**9; i++) {
}
console.timeEnd(2);

$ njs y.js 
1: 13975.273739ms
2: 66203.931495ms

$ node y.js 
1: 855.346ms
2: 863.493ms
```
