### ISSUE TITLE
Misleading, inconsistent semantics of a built-in 'string' type vs 'native' string.

### ISSUE THREAD

**Issue by devgs** [nginx/njs#335]
By built-in type I mean a `string-like` type of properties of `r.headersIn{}` object. It behaves just like a native string, but with a single discrepancy that I have noticed so far (there may be more discrepancies): `String.prototype.indexOf(searchValue [, fromIndex])` ignores value of `fromIndex` and always uses `0`. 

**TL;DR;**

This is a testcase.

nginx.conf
```
...
    location /js_test/1 {
        js_content test1.Handler1;
    }
...
```

test1.js
```
function testCase(name, str) {
    var first_dog_index = str.indexOf('dog');
    var second_dog_index = str.indexOf('dog', first_dog_index + 1);

    return name + ': '
            + first_dog_index + '==' + second_dog_index
            + '; is_tring=' + (str instanceof String)
            + ' type=' + (typeof str)
            + '\n'
            ;
}

function Handler1(request) {
    var results =
        testCase('Case 1', 'The quick brown fox jumps over the lazy dog. If the dog barked, was it really lazy?')
        + testCase('Case 2', new String('The quick brown fox jumps over the lazy dog. If the dog barked, was it really lazy?'))
        + testCase('Case 3', request.headersIn['X-Phrase'])
        + testCase('Case 4', request.headersIn['X-Phrase'].valueOf())
        + testCase('Case 5', request.headersIn['X-Phrase'].toUpperCase())
        + testCase('Case 6', request.headersIn['X-Phrase'].toUpperCase().toLowerCase())
        + testCase('Case 7', new String(request.headersIn['X-Phrase']))
        ;

    request.return(200, results);
}

export default {Handler1};

```

Issue request with **curl**:
```
curl 'http://localhost/js_test/1' --header 'X-Phrase: The quick brown fox jumps over the lazy dog. If the dog barked, was it really lazy?'
```

My output:

```
Case 1: 40==52; is_tring=false type=string
Case 2: 40==52; is_tring=true type=object
Case 3: 40==40; is_tring=false type=string
Case 4: 40==40; is_tring=false type=string
Case 5: -1==-1; is_tring=false type=string
Case 6: 40==40; is_tring=false type=string
Case 7: 40==40; is_tring=true type=object
```

Behaviour is pretty parasitic, even `new String()` conversion does not help. I couldn't find any workaround, so far.

**Comment by xeioex** [comment]
Hi @devgs,

yes, there are [ordinary and byte strings](http://nginx.org/en/docs/njs/reference.html#string) in njs.
All nginx strings are byte-strings.

A byte-string was a workaround for ES5.1 spec and the absence of TypedArray-like types. Currently we are in progress of moving away from this non-standard, subtle behaviour.

The plan is to introduce new properties like `r.variables` -> `r.vars` which would  return a Buffer object (node.js interface) instead of byte-strings in near-term future. In a year, byte-strings will be removed altogether.

Please share your testCase() methods. To convert a byte-string into ordinary try [fromUTF8()](http://nginx.org/en/docs/njs/reference.html#string_fromutf8) method.

**Comment by devgs** [comment]
Hi @xeioex, 

Sorry, by bad. Updated the description with `testCase()` function. I'll try `fromUTF8()` method, thanks.

**Comment by devgs** [comment]
@xeioex, 

Thanks a lot, `fromUTF8()` is a functional workaround, indeed.
