### ISSUE TITLE
 njs does not support modules yet?

### ISSUE THREAD

**Issue by cherishman2005** [nginx/njs#354]
(1) This article shows that njs does not yet support modules：

- [https://www.geek-book.com/src/docs/nginx/nginx/nginx.org/en/docs/njs/node_modules.html](https://www.geek-book.com/src/docs/nginx/nginx/nginx.org/en/docs/njs/node_modules.html)

(2)This article shows that njs supports modules：

- [https://segmentfault.com/a/1190000037677360](https://segmentfault.com/a/1190000037677360)

I want to use this feature to optimze my njs-upsysc-upstream module. such as:
- [https://cherishman2005.github.io/2020/11/01/nginx-upsync-upstream/](https://cherishman2005.github.io/2020/11/01/nginx-upsync-upstream/)

![image](https://user-images.githubusercontent.com/17688273/98223293-dc7d1700-1f8c-11eb-9f38-6f545f2d5ebd.png)

**Comment by xeioex** [comment]
@cherishman2005 

Since 0.3.0 njs supports `ES6 modules`. 

Regarding dynamic load balancing, in a simple case you do not need lua or njs. Use [nginx dns resolver](https://distinctplace.com/2017/04/19/nginx-resolver-explained/).

Alternatively, there is a [memcached way](https://nginx.org/en/docs/http/ngx_http_memcached_module.html). Here you store your key/value pairs in memcached and refer to a specific key in nginx configuration using a variable for proxy_pass.

**Comment by cherishman2005** [comment]
@xeioex 

thx， I will try to  use ES6 modules.



Regarding dynamic load balancing,

client -> nginx -> upstream-server.

(1)microserver is company's ownsystem, upstream-servers register service-center with ip+port, weights etc, not using dns-config.
(2)even upstream-servers's port is changable when restarting;

so nginx-lua/njs use http-API to get service ip+port list from service-center.

**Comment by hongzhidao** [comment]
@xeioex @cherishman2005 

There is another common way to implement `dynamic load balancing`.
1. Each worker process pulls config data from `consul` or `etcd` servers regularly, usually use a timer, then save.
2. Each HTTP request read config from its process and apply it.
The benefit of this is faster read config data.

Now, Lua/OpenResty works well. Much open-source software just put config data into the pure Lua module. For example.
```
-- some-module.lua
local config = {}

local function update_config()
    local data = get_data_from_config_server()
    apply_config(data) -- save data into config variable above.
    ngx.timer(30s, update_config)
end

function http_worker()
    ngx.timer(30s, update_config)
end
```
Notice that the variable `config` always keeps in the worker process.
You need not care about the problem of memory leak because Lua has  GC.

NJS has supported modules, its purpose is to organize js code.
```
-- some-module.js
var config = {}

function blah() {
        ...
}
```
Each HTTP request has an individual variable value of `config`. 
It's totally different from Lua.  And NJS does not support GC.

I also agree that it's useful to support reading/writing data in each worker,
may we can implement it in the future like this.
```
v = kv.get(k)
kv.set(k, v)
```
If it supports, NJS will be able to implement more features, especially for web applications.

**Comment by cherishman2005** [comment]
@hongzhidao 

shared-memory such as 
```
v = kv.get(k)
kv.set(k, v)
```
is especially expected.

because I has implemented dynamic load balancing for consul and self-developed micro-service such as 3 ways:
(1)nginx c module; 
(2)nginx-lua(openresty); 
(3)nginx-njs;

but nginx-njs implements shared-memory(shared_dict) using "fs", but do not perform very well;
