### ISSUE TITLE
njs_regex_compile thread safety

### ISSUE THREAD

**Issue by hytgbn** [nginx/njs#438]
I have found an issue while running some test using njs library.

In njs_pcre.c, [regex_context](https://github.com/nginx/njs/blob/master/src/njs_pcre.c#L17) is declared as a static variable.

When I create multiple VMs in multi threads, the `regex_context` can be nullified by a thread [[1](https://github.com/nginx/njs/blob/master/src/njs_pcre.c#L297)] while other thread is accessing it [[2](https://github.com/nginx/njs/blob/master/src/njs_pcre.c#L369-L379)]

I'm wondering if I'm not using this njs library as designed..

Is njs library supposed to be thread safe if I do not share `vm` objects across multiple threads? would the fix be as simple as making the static variable a thread-local variable?

**Comment by xeioex** [comment]
Hi @hytgbn,

Yes, you are right PCRE usage is not thread-safe, due to the library limitations. This is not an issue for nginx JavaScript module because there is no threads in nginx, because nginx itself[ is not thread-safe either](http://nginx.org/en/docs/dev/development_guide.html#threads_pitfalls).

Meanwhile, PCRE2 support was [landed](https://github.com/nginx/njs/blob/master/src/njs_pcre2.c) last week in the engine and will be available in the next release where this particular issue is solved. Unfortunately, PCRE library still will be used in nginx JavaScript module, because there is still no support for PCRE2 in nginx (but nginx team is working on it).

**Comment by hytgbn** [comment]
Thanks for the prompt answer. will look forward to the release!
