### ISSUE TITLE
Does njs support global variables?

### ISSUE THREAD

**Issue by drinksong** [nginx/njs#598]
njs is a excited for front-end developer and I have a problem now. Before I send response, I need read config from disk to check query string. Considering performance, I want to operate memory, every request I just read from variables from memory and i donot want to readFile from disk.

I try to use js_var, but this variable cannot persist in memory. Do you have any solution of this problem? thanks

**Comment by xeioex** [comment]
Hi @drinksong,

Take a look at [js_preload_object](http://nginx.org/en/docs/http/ngx_http_js_module.html#js_preload_object).

It allows to to preload an immutable JSON file of any size, and that file will be shared across of the requests.

**Comment by HorseLuke** [comment]
Hello, @xeioex .

The object preload from [js_preload_object](http://nginx.org/en/docs/http/ngx_http_js_module.html#js_preload_object) is immutable, means that it can not change values during runtime.

In one scenario is that a developer define a global variable to store config object. Then admin change configs (like route setup, auth, etc) in dashboard, after that njs modify this global variable in runtime. But now it can not do that. A possible way is to use proposal shared dictionary in #437 or [keyval](http://nginx.org/en/docs/http/ngx_http_keyval_module.html#keyval_zone) module , but that will decrease performance because it must run JSON.parse() at every request to restore stored config.

If it has a `js_preload_object_writable` directive that would be fine.

**Comment by xeioex** [comment]
Hi @HorseLuke,

Unfortunately, there a technical limitation for doing `js_preload_object` writable. It is immutable for a reason: it is shared across all the requests virtual machines without any locks or synchronization mechanisms. Once we introduce the synchronization we going to have something similar to shared dictionary or keyval. There is an additional issue on top of that: all the incoming requests are processed by independent worker processes. If we want for changes to `js_preload_object` in one worker to be visible in the other workers we again need shared memory and other synchronization mechanisms on top of that. That leads us to shared dictionary or keyval.
