### ISSUE TITLE
Access ssl connection

### ISSUE THREAD

**Issue by bas-vk** [nginx/njs#633]
Is it possible to access the SSL connection from javascript? I would like to use these 2 functions to derive a shared secret between client and server, https://www.openssl.org/docs/man3.0/man3/SSL_export_keying_material.html.

**Comment by xeioex** [comment]
Hi @bas-vk,

You may use the [filter](http://nginx.org/en/docs/stream/ngx_stream_js_module.html#js_filter) handler in stream module to filter HTTPS connection as a TCP stream. Next, you have to parse TLS protocol messages by yourself., but, I guess it will be But it is not possible to sniff the shared secret between endpoints because it is never sent explicitly AFAIK.

**Comment by bas-vk** [comment]
Thank you for the quick anwser. Not really sure if that it the route I want to go. But I will look into it.
