### ISSUE TITLE
js_preload_object stores non-native Array

### ISSUE THREAD

**Issue by pyhedgehog** [nginx/njs#643]
Minifined example:

`data.json`:
```json
[{"name":"default","value":1},{"name":"other","value":999}]
```
`nginx.conf`:
```
js_preload_object data.json
```
`http.js`:
```javascript
// polyfils {
if(!Object.fromEntries) Object.fromEntries=(l)=>l.reduce((o,it)=>Object.assign(o,{[it[0]]:it[1]}),{});
// }
const dataobj=Object.fromEntries(data.map(o=>[o.name,o.value]));
```
I've got `js exception: TypeError: (intermediate value)["map"] is not a function`.

Investigations:
1. `data.map = undefined`
2. `Array.prototype.map.call(data, o=>[o.name,o.value])` works fine.
3. `const data = JSON.parse(fs.readFileSync('data.json', {'encoding':'utf8'}));` works fine.

**Comment by VadimZhestikov** [comment]
That is by design behavior of preloaded objects, they have only own properties.

**Comment by pyhedgehog** [comment]
@VadimZhestikov Than `Array.isArray` should return `false`.

**Comment by VadimZhestikov** [comment]
No, it should not. Being array is independent of it's prototype chain.

**Comment by VadimZhestikov** [comment]
Please find below small article on
"Understanding of preloaded objects".

Preloaded objects where designed to allow pre-load big known JSON data structures and read-only their elements.

Preloaded objects are by design objects shared between several njs virtual machines.
For this reason they are constant/immutable objects, and they have no prototype chains.

Under the hood, preloaded objects are loaded using following javascript code:

///
text = fs.readFileSync(preloaded_object_file);
globalThis.preloaded_object_name = JSON.parse(
  text,
  function (k,v) {
     if (v instanceof Object) {
         Object.freeze(   Object.setPrototypeOf(v, null) )
     }
     return v
  }
)
///

This means preloaded_object recursively contains "frozen" objects without prototypes.
i.e., no way change prelaoded_object (either nor change values, nor add/remove properties in objects/arrays).


So, you can:

    -- access properties by name, like:

        preloaded_object_name.prop_name
        preloaded_object_name[prop_name_or_index]


    -- enumerate properties, like:
 
        for (i in preloaded_object_name) ......


but since object is not iterable, you can't use:

    for (i of reloaded_object_name) ......


Let me know if you have nay questions.

Thank you!
Vadim

**Comment by pyhedgehog** [comment]
Thanks for clarification. Immutable objects is good reason for nonstandard behaviour. And I've found workaround in advance.
