### ISSUE TITLE
http request from js_body_filter njs script

### ISSUE THREAD

**Issue by kalungedamaji** [nginx/njs#711]
we have a requirement to capture the whole request and response from the upstream 1 . We did this by using the js_body_filter njs script.
Need to send the original response from the upstream 1
Now facing challenges to send the captured request and response body to the  API/SQS/Webhook due to only synchronous code is supported in the js_body_filter njs script
Need help to achieve above requirement.

Detailed configuration please refer  https://gist.github.com/kalungedamaji/251da280f5ecf6e694a70dd28625faf3

**Comment by jo-carter** [comment]
Hello @kalungedamaji 

It'd be better to use [js_content](https://nginx.org/en/docs/http/ngx_http_js_module.html#js_content) rather js_filter for this use-case. It:
A) performs full buffering of the response automatically (and more efficiently than manually creating your own buffer)
B) allows calls to asynchronous functions used to outbound requests such as fetch api (or via [subrequest](https://nginx.org/en/docs/njs/reference.html#r_subrequest)).

Since js_content is a content handler, and you cannot have two content handlers in the same context, a common pattern is to put js_content in location existing location (/hello in your example), and perform subrequest to another (internal) location to perform proxy_pass to backend.

You can then return result to the client, and then send response to external capture endpoint. A very simple (non generic) example:

`
...
location /hello {
    js_content capture.handler;
}

location /_hello {
    internal;
    rewrite ^ /hello;
    ...
    proxy_pass ...
}

#js
async function handler (r) {
    var res = await r.subrequest("/_hello", {body: r.requestBuffer, args: r.variables.args, method: r.method});
    r.return (res.status, res.responseBuffer);
     ....
    <insert fetch call or another subrequest call here to external send res.responseBuffer to upstream endpoint> 
}
export default {handler}
`

Finally, if you still must use js_body_filter for some reason - you may also be able to leverage an undocumented nginx directive `post_action <location>` which will process the specified location *after* regular content phase - I'd advise against that approach unless there are no other options as it's quite the hack (and due it being undocumented).
