### ISSUE TITLE
r.return doesn't exit/return if called in IF condition

### ISSUE THREAD

**Issue by lancedockins** [nginx/njs#767]
It does not appear that NJS respects the use of r.return if used in conjunction with js_set and an IF block.  There may be other conditions that would trigger this as well but at the very least, you can replicate it on NJS 0.8.5 by doing the following:

In nginx.conf
```
js_set $variable something.funcname;
```

Elsewhere (e.g. in a specific vhost)

```
if ($variable = 1){
  // something
}
```

In the JS code:

```
function funcname(r){
   r.return(403);
   return;
}
```

It doesn't seem to matter whether you return anything, return empty, or remove the return function entirely.  The r.return statement doesn't run.

Yes.  I realize that you could just add a 403 return inside of the IF block.  But there are cases where you might have other JS variables declared as js_var in NJS that could trigger the need to branch differently than what you would normally do in an Nginx IF block.  So ideally, you shouldn't have to have multiple IF blocks in the Nginx conf in order for r.return to work in NJS.

Given that the 403 would have to terminate the request in the middle of Nginx evaluating a variable, I realize that this "might" be the sort of thing that is not possible in NJS itself.  If that is the case, then the documentation for NJS should clarify where r.return cannot be used.  But if it is possible to use r.return for most NJS code that isn't a header/body filter, then it seems like this is some sort of bug.

Is there some reason that r.return can't be used inside of a js_set var that is triggered by an IF block (or anything else I suppose)?

**Comment by xeioex** [comment]
Hi @lancedockins,

What is happening with this setup:

`r.return(403)` is actually called as a $variable handler. 
But because it has no body argument and it is an error code, the status code is [set](https://github.com/nginx/njs/blob/master/nginx/ngx_http_js_module.c#L2728) to a `ctx->status` to be returned at the end of `js_content`. Because you have no `js_content` it is effectively ignored.
The reason we do not want to call `ngx_http_send_response()` all the time is that we want to preserve a standard 4xx response from NGINX.

To make r.return(403) to send the response right away is to add some body
for example `r.return(403, "Access denied")`. Note that `r.return(403, "")` will not work as expected until 0.8.6 due to [this](https://github.com/nginx/njs/pull/787).

The second reason I am hesitant to "fix" it by always calling `ngx_http_send_response()`, is that it may brake already existing njs scripts.

**Comment by lancedockins** [comment]
Tnanks, Dmitry.  While I guess you could still call this a bug of sorts, the fact that you can work around that bug by including a body in the r.return call is sufficient in my mind.  It would definitely cover my use case.  It's a bit of a niche scenario so I don't know that that type of problem will manifest for a lot of NJS users.  In the meantime, I have this and a few other solutions that I can use to address this.  Thank you for getting back to me.
